import os
import re
import subprocess
from datetime import datetime
from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential

# ----------------------------
# 1️⃣ Connect to Azure OpenAI
# ----------------------------
project = AIProjectClient(
    endpoint="https://ryancoffman-5902-resource.services.ai.azure.com/api/projects/ryancoffman-5902",
    credential=DefaultAzureCredential(),
)
models = project.get_openai_client(api_version="2024-10-21")

# ----------------------------
# 2️⃣ Ask GPT-4o for code
# ----------------------------
response = models.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role": "system",
            "content": (
                "You are a highly skilled software developer. "
                "Always return *only* valid code wrapped in triple backticks with a language tag. "
                "You may write Python 3.10.18 or C++17 code. "
                "Avoid any GUI libraries, file I/O, or plt.show(). "
                "All outputs should be printed to the terminal (stdout)."
            ),
        },
        {
            "role": "user",
            "content": "Write a simple C++ program that prints the first 20 Fibonacci numbers.",
        },
    ],
)

content = response.choices[0].message.content
print("🧠 Model output:\n", content)

# ----------------------------
# 3️⃣ Extract code + language
# ----------------------------
match = re.search(r"```(\w+)?\n([\s\S]*?)```", content)
if not match:
    raise ValueError("❌ Could not find code block in model response!")

lang = match.group(1) or "python"
code = match.group(2).strip()

print(f"📘 Detected language: {lang}")

# ----------------------------
# 4️⃣ Prepare output folders
# ----------------------------
os.makedirs("generated", exist_ok=True)
os.makedirs("envs", exist_ok=True)
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

# ----------------------------
# 5️⃣ Run based on language
# ----------------------------
if lang.lower() in ("cpp", "c++"):
    # ---- Handle C++ ----
    cpp_path = f"generated/generated_script_{timestamp}.cpp"
    with open(cpp_path, "w", encoding="utf-8") as f:
        f.write("// Generated by Azure GPT-4o\n\n")
        f.write(code)

    print(f"💾 Saved C++ code to: {cpp_path}")

    exe_path = f"generated/a_{timestamp}.out"
    print("🧱 Compiling with g++...")
    compile_result = subprocess.run(["g++", "-std=c++17", cpp_path, "-o", exe_path], capture_output=True, text=True)

    if compile_result.returncode != 0:
        print("❌ Compilation failed:\n", compile_result.stderr)
    else:
        print("🚀 Running compiled C++ binary...\n")
        result = subprocess.run([exe_path], capture_output=True, text=True)
        print("📤 STDOUT:\n", result.stdout)
        if result.stderr:
            print("⚠️ STDERR:\n", result.stderr)

elif lang.lower() == "python":
    # ---- Handle Python ----
    py_path = f"generated/generated_script_{timestamp}.py"
    with open(py_path, "w", encoding="utf-8") as f:
        f.write("# Generated by Azure GPT-4o\n\n")
        f.write(code)

    print(f"💾 Saved Python script to: {py_path}")

    # Detect dependencies
    reqs = re.findall(r"#\s*requirements:\s*(.*)", code)
    imports = re.findall(r"import\s+([a-zA-Z0-9_]+)", code)
    dependencies = set()
    for r in reqs:
        dependencies.update(re.split(r"[ ,]+", r.strip()))
    dependencies.update(imports)
    skip_libs = {"os", "sys", "re", "math", "subprocess", "datetime", "json"}
    dependencies = [d for d in dependencies if d and d not in skip_libs]

    venv_path = f"envs/env_{timestamp}"
    print(f"🧱 Creating virtual environment: {venv_path}")
    subprocess.run(["python3", "-m", "venv", venv_path], check=True)

    pip_executable = os.path.join(venv_path, "bin", "pip")
    python_executable = os.path.join(venv_path, "bin", "python")

    if dependencies:
        print(f"📦 Installing dependencies: {dependencies}")
        subprocess.run([pip_executable, "install", *dependencies], check=False)
    else:
        print("✅ No external dependencies detected.")

    print("🚀 Running Python script...\n")
    result = subprocess.run([python_executable, py_path], capture_output=True, text=True, timeout=15)
    print("📤 STDOUT:\n", result.stdout)
    if result.stderr:
        print("⚠️ STDERR:\n", result.stderr)

else:
    print(f"❌ Unsupported language: {lang}")

print("\n✅ Completed run at:", timestamp)
