import os
import re
import subprocess
from datetime import datetime
from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential

# ----------------------------
# 1️⃣ Connect to Azure OpenAI
# ----------------------------
project = AIProjectClient(
    endpoint="https://ryancoffman-5902-resource.services.ai.azure.com/api/projects/ryancoffman-5902",
    credential=DefaultAzureCredential(),
)
models = project.get_openai_client(api_version="2024-10-21")

# ----------------------------
# 2️⃣ Ask GPT-4o for C++ code
# ----------------------------
response = models.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role": "system",
            "content": (
                "You are a highly skilled software developer. "
                "Always return *only* valid C++17 code wrapped in triple backticks. "
                "Avoid any GUI libraries. "
                "All outputs should be printed to the terminal (stdout)."
            ),
        },
        {
            "role": "user",
            "content": "Write a C++ program that encrypts and dycripts a file .",
        },
    ],
)

content = response.choices[0].message.content

# ----------------------------
# 3️⃣ Extract C++ code
# ----------------------------
match = re.search(r"```(?:cpp|c\+\+)?\n([\s\S]*?)```", content)
if not match:
    raise ValueError("❌ Could not find C++ code block in model response!")

code = match.group(1).strip()
print("🧠 Extracted C++ code:\n", code)

# ----------------------------
# 4️⃣ Prepare output folder
# ----------------------------
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
nested_dir = f"generated/crypt"
os.makedirs(nested_dir, exist_ok=True)

cpp_path = os.path.join(nested_dir, f"generated_script_{timestamp}.cpp")
exe_path = os.path.join(nested_dir, f"a_{timestamp}.out")

# ----------------------------
# 5️⃣ Save C++ code
# ----------------------------
with open(cpp_path, "w", encoding="utf-8") as f:
    f.write("// Generated by Azure GPT-4o\n\n")
    f.write(code)
print(f"💾 Saved C++ code to: {cpp_path}")

# ----------------------------
# 6️⃣ Compile and run
# ----------------------------
print("🧱 Compiling with g++...")
compile_result = subprocess.run(["g++", "-std=c++17", cpp_path, "-o", exe_path],
                                capture_output=True, text=True)

if compile_result.returncode != 0:
    print("❌ Compilation failed:\n", compile_result.stderr)
else:
    print("🚀 Running compiled C++ binary...\n")
    result = subprocess.run([exe_path], capture_output=True, text=True)
    print("📤 STDOUT:\n", result.stdout)
    if result.stderr:
        print("⚠️ STDERR:\n", result.stderr)

print("\n✅ Completed run at:", timestamp)
